---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: vault-backup
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vault-backup
  data:
    - secretKey: aws_credentials
      remoteRef:
        key: accounts/holecs
        property: awscli_credentials
    - secretKey: backup_rotate
      remoteRef:
        key: vault-backup/config
        property: backup_rotate
    - secretKey: vault_addr
      remoteRef:
        key: vault-backup/config
        property: vault_addr
    - secretKey: s3_endpoint
      remoteRef:
        key: vault-backup/config
        property: s3_endpoint
    - secretKey: s3_bucket_uri
      remoteRef:
        key: vault-backup/config
        property: s3_bucket_uri
    - secretKey: gpg_recipient
      remoteRef:
        key: vault-backup/config
        property: gpg_recipient
    - secretKey: gpg_pub_key
      remoteRef:
        key: vault-backup/config
        property: gpg_pub_key
